---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 8f8959d375d95e71103239a04d1b4c8431809ced
    app.quarkus.io/build-timestamp: 2023-11-22 - 17:26:06 +0000
  labels:
    app.kubernetes.io/name: ssbd03
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: ssbd03
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: ssbd03
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 8f8959d375d95e71103239a04d1b4c8431809ced
    app.quarkus.io/build-timestamp: 2023-11-22 - 17:26:06 +0000
  labels:
    app.kubernetes.io/name: ssbd03
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: ssbd03
spec:
  dockerImageRepository: docker.io/miszczu1902/quarkus-ssbd202303
  lookupPolicy:
    local: true
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 8f8959d375d95e71103239a04d1b4c8431809ced
    app.quarkus.io/build-timestamp: 2023-11-22 - 17:26:06 +0000
  labels:
    app.kubernetes.io/name: ssbd03
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: ssbd03
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: ssbd03
    app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: <<unknown>>
        app.quarkus.io/commit-id: 8f8959d375d95e71103239a04d1b4c8431809ced
        app.quarkus.io/build-timestamp: 2023-11-22 - 17:26:06 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/name: ssbd03
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - env:
            - name: tua202303
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: miszczu1902/quarkus-ssbd202303:1.0.0
          imagePullPolicy: Always
          name: ssbd03
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - ssbd03
        from:
          kind: ImageStreamTag
          name: ssbd03:1.0.0
      type: ImageChange
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 8f8959d375d95e71103239a04d1b4c8431809ced
    app.quarkus.io/build-timestamp: 2023-11-22 - 17:26:06 +0000
  labels:
    app.kubernetes.io/name: ssbd03
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: ssbd03
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: ssbd03
