create table account
(
    id                          bigint generated by default as identity
        primary key,
    creation_date_time          timestamp                               not null,
    last_modification_date_time timestamp,
    version                     bigint,
    email                       varchar(255)                            not null
        constraint unique_email
            unique,
    is_active                   boolean default false                   not null,
    is_enable                   boolean default false                   not null,
    language_                   varchar default 'PL'::character varying not null,
    password                    varchar(60)                             not null,
    register_date               timestamp                               not null,
    username                    varchar(16)                             not null
        constraint unique_username
            unique,
    created_by                  bigint
        constraint fkatwoepbie7ousm3au0cp7hira
            references account,
    last_modified_by            bigint
        constraint fkgvr2il8ft207ll7wiyt3q3lhr
            references account
);

create table access_level_mapping
(
    access_level                varchar(31)          not null,
    id                          bigint generated by default as identity
        primary key,
    creation_date_time          timestamp            not null,
    last_modification_date_time timestamp,
    version                     bigint,
    is_active                   boolean default true not null,
    created_by                  bigint
        constraint fk63mgqvcb0vdfseccqok6it97n
            references account,
    last_modified_by            bigint
        constraint fk7vogy2yc430e0smdago526fyb
            references account,
    account_id                  bigint               not null
        constraint fkj8wjikglfth8knf8n7t1338ic
            references account,
    constraint access_level_account_unique_constraint
        unique (account_id, access_level)
);

create index access_level_mapping_account_id
    on access_level_mapping (account_id);

create table account_confirmation_token
(
    id                          bigint generated by default as identity
        primary key,
    creation_date_time          timestamp             not null,
    last_modification_date_time timestamp,
    version                     bigint,
    expiration_date             timestamp             not null,
    is_reminder_sent            boolean default false not null,
    token_value                 varchar(10)           not null
        constraint uk_cy8jaherrxbsa2uvi9e04j6rf
            unique,
    created_by                  bigint
        constraint fk2imh22461b5qxg0nn2jgril9m
            references account,
    last_modified_by            bigint
        constraint fkb8wv65653ei9u3o2sr5bpu6to
            references account,
    account_id                  bigint
        constraint fkax6m3bhchub4vregkdu7q9wba
            references account
);

create table address
(
    id                          bigint generated by default as identity
        primary key,
    creation_date_time          timestamp    not null,
    last_modification_date_time timestamp,
    version                     bigint,
    building_number             varchar(255) not null,
    city                        varchar(32)  not null,
    postal_code                 varchar(6)   not null,
    street                      varchar(32)  not null,
    created_by                  bigint
        constraint fksgrw3por9aufp2t5xeml8ohvb
            references account,
    last_modified_by            bigint
        constraint fkr88xose7l0wy3ko6lmux25oy7
            references account
);

create table admin
(
    id bigint not null
        primary key
        constraint fknidjm7nhdy2jem07qu7kmnbuf
            references access_level_mapping
);

create table email_confirmation_token
(
    id                          bigint generated by default as identity
        primary key,
    creation_date_time          timestamp    not null,
    last_modification_date_time timestamp,
    version                     bigint,
    email                       varchar(255) not null,
    expiration_date             timestamp    not null,
    token_value                 varchar(10)  not null
        constraint uk_n2a73y2n1mo25ug39yokve4sg
            unique,
    created_by                  bigint
        constraint fkanfl9lhljaqirgt790jo0rmyi
            references account,
    last_modified_by            bigint
        constraint fk754x181wlc34tf2c2jv75hjei
            references account,
    account_id                  bigint
        constraint fka171uhvsqfanolh5k455ck1lv
            references account
);

create table heat_distribution_centre
(
    id                          bigint generated by default as identity
        primary key,
    creation_date_time          timestamp not null,
    last_modification_date_time timestamp,
    version                     bigint,
    created_by                  bigint
        constraint fkd47jmquprokyly2fty9uxnc8
            references account,
    last_modified_by            bigint
        constraint fkhosvyiqika5odrdf96ecliav8
            references account
);

create table building
(
    id                          bigint generated by default as identity
        primary key,
    creation_date_time          timestamp      not null,
    last_modification_date_time timestamp,
    version                     bigint,
    communal_area_aggregate     numeric(10, 2) not null,
    total_area                  numeric(10, 2) not null,
    created_by                  bigint
        constraint fki80r2xi7h43hxlkmqe63r8scw
            references account,
    last_modified_by            bigint
        constraint fkfw9729j6v44lm1vfucc01v2x7
            references account,
    address_id                  bigint
        constraint fkf3ryyh4bd143l5b8stt65hwgr
            references address,
    heat_distribution_centre_id bigint
        constraint fko4d3qly5a8niwij8v9bnf083u
            references heat_distribution_centre
);

create index building_address_id
    on building (address_id);

create index building_heat_distribution_centre_id
    on building (heat_distribution_centre_id);

create table login_data
(
    creation_date_time          timestamp not null,
    last_modification_date_time timestamp,
    version                     bigint,
    invalid_login_counter       integer default 0
        constraint login_data_invalid_login_counter_check
            check ((invalid_login_counter <= 3) AND (invalid_login_counter >= 0)),
    last_invalid_logic_address  varchar(15),
    last_invalid_login_date     timestamp,
    last_valid_logic_address    varchar(15),
    last_valid_login_date       timestamp,
    id                          bigint    not null
        primary key
        constraint fkmlf0mmnagk8rwl8ayfnw11x7a
            references account,
    created_by                  bigint
        constraint fki3c8ekpqb2ymeyydtnxiqvcq
            references account,
    last_modified_by            bigint
        constraint fke7yf7v77embgfx77oysq2rlk9
            references account
);

create table manager
(
    license varchar(20) not null
        constraint unique_license
            unique,
    id      bigint      not null
        primary key
        constraint fkav7t7svax9knx8v67ayay95jk
            references access_level_mapping
);

create table heat_distribution_centre_pay_off
(
    id                          bigint generated by default as identity
        primary key,
    creation_date_time          timestamp      not null,
    last_modification_date_time timestamp,
    version                     bigint,
    consumption                 numeric(10, 2) not null,
    consumption_cost            numeric(10, 2) not null,
    date_                       date           not null,
    heating_area_factor         numeric(3, 2)  not null,
    created_by                  bigint
        constraint fkk1qp4tpeyxproiqauu7936ol2
            references account,
    last_modified_by            bigint
        constraint fkl8oe2epg9boumibx2ttymnsn8
            references account,
    heat_distribution_centre_id bigint
        constraint fkcuiqxei6vk0h7i3r71f28xlp4
            references heat_distribution_centre,
    manager_id                  bigint
        constraint fk6nl12o1i7jc05p65xe86gqrat
            references manager
);

create index heat_distribution_centre_pay_off_heat_distribution_centre_id
    on heat_distribution_centre_pay_off (heat_distribution_centre_id);

create index heat_distribution_centre_pay_off_manager_id
    on heat_distribution_centre_pay_off (manager_id);

create table owner
(
    phone_number varchar(9) not null
        constraint unique_phone_number
            unique,
    id           bigint     not null
        primary key
        constraint fkeqs4k6k9mji4dnf40saxnkkw4
            references access_level_mapping
);

create table personal_data
(
    creation_date_time          timestamp   not null,
    last_modification_date_time timestamp,
    version                     bigint,
    first_name                  varchar(32) not null,
    surname                     varchar(32) not null,
    id                          bigint      not null
        primary key
        constraint fkcmjo15l01dgohx2dft430h0uq
            references account,
    created_by                  bigint
        constraint fks470wl5u72uwblooefohytyov
            references account,
    last_modified_by            bigint
        constraint fkc66lfoq7nth99rp6i3rcwswr6
            references account
);

create table place
(
    id                              bigint generated by default as identity
        primary key,
    creation_date_time              timestamp      not null,
    last_modification_date_time     timestamp,
    version                         bigint,
    area                            numeric(10, 2) not null,
    central_heating_connection      boolean        not null,
    hot_water_connection            boolean        not null,
    place_number                    smallint       not null,
    predicted_hot_water_consumption numeric(10, 2) not null,
    created_by                      bigint
        constraint fkpb7aybd3e9ixemls630l3yqj4
            references account,
    last_modified_by                bigint
        constraint fkonmr3x4gnfu4vcjb96ompskmo
            references account,
    building_id                     bigint
        constraint fkn04ei470wm49ma8kceoqhqgln
            references building,
    owner_id                        bigint
        constraint fksaeqp6jy1tp6utnuacyc2u0g9
            references owner,
    constraint place_number_building_id_unique_constraint
        unique (place_number, building_id)
);

create table advance
(
    id                          bigint generated by default as identity
        primary key,
    creation_date_time          timestamp not null,
    last_modification_date_time timestamp,
    version                     bigint,
    date_                       date      not null,
    created_by                  bigint
        constraint fkcjjltiqe3eq9lnd4ptrxs8b0h
            references account,
    last_modified_by            bigint
        constraint fkiiaseanbhsdttsvw2xxyrk249
            references account,
    place_id                    bigint
        constraint fkdn2cimvrpyxxdtbej5b8fc32u
            references place
);

create index advance_place_id
    on advance (place_id);

create table annual_balance
(
    id                                  bigint generated by default as identity
        primary key,
    creation_date_time                  timestamp      not null,
    last_modification_date_time         timestamp,
    version                             bigint,
    total_heating_communal_area_advance numeric(10, 2) not null,
    total_heating_communal_area_cost    numeric(10, 2) not null,
    total_heating_place_advance         numeric(10, 2) not null,
    total_heating_place_cost            numeric(10, 2) not null,
    total_hot_water_advance             numeric(10, 2) not null,
    total_hot_water_cost                numeric(10, 2) not null,
    year_                               smallint       not null
        constraint annual_balance_year__check
            check (year_ >= 2021),
    created_by                          bigint
        constraint fkjmul0yghnau52kf798fddsbsj
            references account,
    last_modified_by                    bigint
        constraint fkkpp0c8g4y9mh3hay3qa9kwc5q
            references account,
    place_id                            bigint
        constraint fknp71khb3e2wq3ouxtcr6j3qvm
            references place
);

create index annual_balance_place_id
    on annual_balance (place_id);

create table heating_place_and_communal_area_advance
(
    advance_change_factor               numeric(19, 2) not null
        constraint heating_place_and_communal_area_adv_advance_change_factor_check
            check ((advance_change_factor >= (0)::numeric) AND (advance_change_factor <= (9)::numeric)),
    heating_communal_area_advance_value numeric(10, 2) not null,
    heating_place_advance_value         numeric(10, 2) not null,
    id                                  bigint         not null
        primary key
        constraint fk8nfx5s2i2raq7bmdvpa5km2fw
            references advance
);

create table hot_water_advance
(
    hot_water_advance_value numeric(10, 2) not null,
    id                      bigint         not null
        primary key
        constraint fkf4l3asn8xv509119qte8ahq66
            references advance
);

create table hot_water_entry
(
    id                          bigint generated by default as identity
        primary key,
    creation_date_time          timestamp      not null,
    last_modification_date_time timestamp,
    version                     bigint,
    date_                       date           not null,
    entry_value                 numeric(10, 2) not null,
    created_by                  bigint
        constraint fk5k126ftl1n213k7e6ojx44nvd
            references account,
    last_modified_by            bigint
        constraint fk1gl0db5gfta7kr0vg6s30hj7k
            references account,
    manager_id                  bigint
        constraint fk67wg6s2dwp6q5bmy2cthl3w2q
            references manager,
    place_id                    bigint
        constraint fk7rjsw057ugt1w73tnjsucsio2
            references place
);

create index hot_water_entry_place_id
    on hot_water_entry (place_id);

create index hot_water_entry_manager_id
    on hot_water_entry (manager_id);

create table month_pay_off
(
    id                          bigint generated by default as identity
        primary key,
    creation_date_time          timestamp      not null,
    last_modification_date_time timestamp,
    version                     bigint,
    central_heating_unit_cost   numeric(10, 2) not null,
    hot_water_consumption       numeric(10, 2) not null,
    payoff_date                 date           not null,
    water_heating_unit_cost     numeric(10, 2) not null,
    created_by                  bigint
        constraint fkmctqhfig3wp50rcr03yhw3gde
            references account,
    last_modified_by            bigint
        constraint fkfd44lbk0ehyc98ttdx4r5qfao
            references account,
    owner_id                    bigint
        constraint fkbwll2amp2sx88j71ootm0nwot
            references owner,
    place_id                    bigint
        constraint fknm98eib8i3pyppcpqf6i2uwpw
            references place
);

create index month_pay_off_place_id
    on month_pay_off (place_id);

create index month_pay_off_owner_id
    on month_pay_off (owner_id);

create table past_quarter_hot_water_pay_off
(
    creation_date_time          timestamp      not null,
    last_modification_date_time timestamp,
    version                     bigint,
    average_consumption         numeric(10, 2) not null
        constraint past_quarter_hot_water_pay_off_average_consumption_check
            check (average_consumption >= (0)::numeric),
    days_number_in_quarter      integer        not null
        constraint past_quarter_hot_water_pay_off_days_number_in_quarter_check
            check ((days_number_in_quarter >= 90) AND (days_number_in_quarter <= 92)),
    id                          bigint         not null
        primary key
        constraint fkmisg78uccabuatgu8b0hcuhq
            references place,
    created_by                  bigint
        constraint fk930rrwjgnk9kwbl1ev5v3u1mr
            references account,
    last_modified_by            bigint
        constraint fksawcoehfkds571ssuaoldkbpb
            references account
);

create index place_building_id
    on place (building_id);

create index place_owner_id
    on place (owner_id);

create table reset_password_token
(
    id                          bigint generated by default as identity
        primary key,
    creation_date_time          timestamp   not null,
    last_modification_date_time timestamp,
    version                     bigint,
    expiration_date             timestamp   not null,
    token_value                 varchar(10) not null
        constraint uk_krhu6pfeu0tf345d8bgy8ghmm
            unique,
    created_by                  bigint
        constraint fkl40r4coo4p5grhel977sd092i
            references account,
    last_modified_by            bigint
        constraint fkqqj6cpss2rosptcxd0b2s5fep
            references account,
    account_id                  bigint
        constraint fkf8fxk9jthoxy8c8vrl05r7h40
            references account
);