version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./secrets/certs:/etc/ssl/certs
      - ./secrets/private:/etc/ssl/private
      - ./secrets/snippets:/etc/nginx/snippets
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://appserver:8080/api/health-check" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5
    depends_on:
      appserver:
        condition: service_started

  appserver:
    container_name: appserver
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
#      - "4848:4848"
#      - "9009:9009"
      - "9990:9990"
    environment:
      - JVM_ARGS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9009
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8080/api/health-check" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ssbd03
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./create_db_users.sh:/docker-entrypoint-initdb.d/create_db_users.sh
      - ./init.sql:/init.sql
      - ./createDB.sql:/createDB.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5